### ISSUE TITLE
Replace `samalba/dockerclient` library

### ISSUE THREAD

**Issue by alexei-led** [gaia-adm/pumba#14]
Replace [samalba/dockerclient](https://github.com/samalba/dockerclient) library with official Docker Go [docker/engine-api](https://github.com/docker/engine-api)

**Comment by bartoszmajsak** [comment]
Just for the record, this repository is deprecated.

It's been moved to the main docker repo

- https://github.com/docker/docker/tree/master/client
- https://github.com/docker/docker/tree/master/api/types

**Comment by alexei-led** [comment]
Done.
