### ISSUE TITLE
netem: add check for `iptools2` install

### ISSUE THREAD

**Issue by alexei-led** [gaia-adm/pumba#21]
The `netem` functionality requires `tc` tool. `tc` is part of `iptools2` package, that's why it's important to check if this package is installed.

**Comment by justincormack** [comment]
You should be able to avoid requiring `tc` to be in all containers, as you can run commands in the network namespace of another container:

```
docker run -dit --name alp alpine sh
# I happen to know this container has tc in, any other will do
docker run --net=container:alp justincormack/debian tc
```

This will run the `tc` command but using the network of the alpine container, so you can set the properties of that container. This should make it easier to use for unmodified code.

**Comment by alexei-led** [comment]
@justincormack thank you, cool tip. Will try it.

**Comment by alexei-led** [comment]
`--tc` flag to specify Docker image containing `tc` tool
