### ISSUE TITLE
Unable to start the pumba container

### ISSUE THREAD

**Issue by Kumaravel2904** [gaia-adm/pumba#27]
docker run -v /var/run/docker.sock:/var/run/docker.sock gaiaadm/pumba pumba kill --interval 10s --signal SIGTERM ^compo
Incorrect Usage.

NAME:
   pumba kill - kill specified containers

USAGE:
   pumba kill [command options] containers (name, list of names, RE2 regex)

DESCRIPTION:
   send termination signal to the main process inside target container(s)

OPTIONS:
   --signal value, -s value  termination signal, that will be sent by Pumba to the main process inside target container(s) (default: "SIGKILL")

time="2016-10-31T12:46:33Z" level=fatal msg="flag provided but not defined: -interval"

**Comment by alexei-led** [comment]
`--interval` is a global option for `pumba` command, i.e. right syntax in your case would be:
```
$ pumba --interval 10s kill --signal SIGTERM ^compo
```

to see all global flags run `pumba --help`
to see `kill` command flags, run `pumba kill --help`

**Comment by alexei-led** [comment]
There was an error in README file. I fixed it. Sorry.

**Comment by Kumaravel2904** [comment]
It works direct but as docker container it's gives the error

Regards,
Kumaravel
9029930068
