### ISSUE TITLE
Debug messages problem

### ISSUE THREAD

**Issue by delta-bravo** [gaia-adm/pumba#28]
When running:

`
$ pumba --debug netem -d 60000ms delay -t 5000 -j 100 -c 50 mr_biggles
`

Getting this output:

`DEBU[0000] No interval, running only once`
`DEBU[0000] SHIT4`

Is it expected?

`
$ pumba -v
Pumba version 0.3.0 - cac0eb1 (master) 2016-11-24_13:07_GMT
`

Thanks!

**Comment by alexei-led** [comment]
Yes, it's designed behavior. Pumba can run *chaos* task once or periodically. 
You can use `pumba --interval` (global option) to specify recurrent interval.

Regarding "improper" debug message :) , I will remove it (just skipped my eyes)
