### ISSUE TITLE
"pumba rm" without "--force" flag is useless

### ISSUE THREAD

**Issue by slnowak** [gaia-adm/pumba#30]
If you try to remove running docker container without providing '-f' flag, docker deamon yields:
```
novy@novy-K53SV:~/Desktop$ docker rm foo
Error response from daemon: You cannot remove a running container 1c0ea1d039e4db47e194040efa950647cd136ce961e828646def8859cb95f146. Stop the container before attempting removal or use -f
```

The conclusion is that running `docker rm container` only allows you to remove stopped container.

However, removing stopped container with pumba is impossible. Deep under the hood, pumba does the following call using samalba docker client:
`runningContainers, err := client.api.ListContainers(false, false, "")
`which always returns only running containers. 

We should either fix it or provide '--force' flag by default.

**Comment by alexei-led** [comment]
I saw you did it. Thank you for contributing!
