### ISSUE TITLE
Pumba does not seem to work in my environment

### ISSUE THREAD

**Issue by tomekit** [gaia-adm/pumba#33]
Hi,
I've problem setting up Panda.

My plan is to test how Elasticsearch can deal with network delays / interruptions. 

I've copied the Panda i386 binary on my Ubuntu 16.04 to `/usr/bin/local/panda`. The `amd64` version didn't seem to work for me (even after chmod +x applied):
> /tmp$ ./pumba_linux_amd64
> bash: ./pumba_linux_amd64: No such file or directory

My containers I want to test do not have `tc` installed, so I've wanted to use the `-tc-image` flag.
Here is my pumba command:
> /tmp$ pumba netem -tc-image gaiadocker/iproute2 --duration 5m delay --time 3000 027158df58f3
> INFO[0000] netem: delay for containers           

I've `gaiadocker/iproute2` image in my `docker images`

I would expect that outgoing ping on the `027158df58f3` will slow down, but that's not the case.

What I am doing wrong? Thanks

PS.
Here is my test ES cluster:
> 027158df58f3        itzg/elasticsearch   "/start"                 About an hour ago   Up About an hour    9200/tcp, 9300/tcp                               elasticsearchcluster_master3_1
> 6d273f3bbbe0        itzg/elasticsearch   "/start"                 About an hour ago   Up About an hour    9200/tcp, 9300/tcp                               elasticsearchcluster_data_remote_1
> 9be89c4887bd        itzg/elasticsearch   "/start"                 About an hour ago   Up About an hour    9200/tcp, 9300/tcp                               elasticsearchcluster_master2_1
> 532422cfe871        itzg/elasticsearch   "/start"                 About an hour ago   Up About an hour    9300/tcp, 0.0.0.0:9201->9200/tcp                 elasticsearchcluster_master1_1
>

**Comment by alexei-led** [comment]
First, it seems that I've compiled Pumba with C Runtime (musl). My mistake. Will fix it.

**Comment by alexei-led** [comment]
I've fixed `pumba_linux_amd64` to be statically linked (instead of dynamically linked with C runtime). Now you should be able to run it without a problem.

`pumba` supports finding containers **by name, name list, regex (name)** only. **Container ID** is not supported.

And you also need to pull `iproute2` image beforehand:  `docker pull gaiadocker/iproute2` (or any other image that has `iproute2` package installed)

**Comment by tomekit** [comment]
Hi, thanks for your answer. Still no luck

```
/tmp$ ./pumba_darwin_amd64 
bash: ./pumba_darwin_amd64: cannot execute binary file: Exec format error
```

```
/tmp$ uname -a
Linux my-Asus 4.6.0-040600-generic #201606100558 SMP Fri Jun 10 10:01:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tomekit** [comment]
That's awesome, it works now. Thanks !

**Comment by tomekit** [comment]
It looks like the v.0.4.1 has some issues as well:
https://github.com/gaia-adm/pumba/releases/download/0.4.1/pumba_linux_amd64
Getting: "No such file or directory"

**Comment by syndr0m** [comment]
same for v0.4.6 (https://github.com/gaia-adm/pumba/releases/download/0.4.6/pumba_linux_amd64)

```
$> readelf -a pumba_linux_amd64
(...)
  INTERP         0x0000000000000fe7 0x0000000000400fe7 0x0000000000400fe7
                 0x0000000000000019 0x0000000000000019  R      0x1
      [Requesting program interpreter: /lib/ld-musl-x86_64.so.1]
```

**Comment by alexei-led** [comment]
@syndr0m thank you, will fix

**Comment by alexei-led** [comment]
@syndr0m fixed, try again

**Comment by syndr0m** [comment]
it works, thank you :)
(great project btw ;) )
