### ISSUE TITLE
tc command check

### ISSUE THREAD

**Issue by tarqe39** [gaia-adm/pumba#35]
Hi, i had a problem trying to run pumba on CentOS 7.3 with installed iproute package, as it returned error:
`ERRO[0000] command 'tc' not found inside the ...`

As it turns out after debugging, the command existed, but the default permissions would not allow it to execute. Maybe it would be good to add additional check when verifying `checkInspect.ExitCode != 0 ` for value 126 (error: "Command invoked cannot execute"), and possibly other specific exit codes (http://tldp.org/LDP/abs/html/exitcodes.html)

This could prevent unneeded head scratching for users :)

EDIT: also, there is a presumption that `which` command exists on the system, but that command may also fail

**Comment by alexei-led** [comment]
Thank you for report, will take a look

**Comment by Tyson1986** [comment]
@tarqe39 if i understand correctly you try to 'run pumba on CentOS 7.3 with installed iproute package'. But 'tc' should be in target container, not in pumba. To avoid changes inside target container you can use:
'--tc-image gaiadocker/iproute2'
Look at README.

**Comment by alexei-led** [comment]
`--tc-image gaiadocker/iproute2` is the right solution, indeed @tarqe39 

This will run a "sidekick" container with `tc` on board and connect it to the same network as your target container `--network=container:target-container`
