### ISSUE TITLE
Pumba interact with all containers inside docker

### ISSUE THREAD

**Issue by Tyson1986** [gaia-adm/pumba#41]
I have Jenkins server, based on docker. All workers are containers, each job starts containers in specific docker network. But each pumba run can affect any container, not only inside my network. Regexp helps, but in case of big amount of job\containers my regexp can match other container, and i will fail someones tests/build/etc. 
Good enhancement will be add ability to work with only current docker network.
--label com.gaiaadm.pumba.skip=true is good point, but it handle a bit different problem. I can't add this flag to all images across all company. So for now solution is - add project-specific name of containers.

**Comment by alexei-led** [comment]
You can add `--label com.gaiaadm.pumba.skip=true` to a Docker container when you are running it. No need to add "skip" label at build time.
If you know specific names, Pumba supports list of containers names too.
Another option to add some unique prefix to containers you want to test and define a regex.

I'm open to other options too

**Comment by bsideup** [comment]
Hi @alexei-led,

Without the white-labeling, it's not possible to use Pumba in CI environments where multiple jobs share the same Docker daemon.
