### ISSUE TITLE
netem command fails on images where user != root

### ISSUE THREAD

**Issue by polson136** [gaia-adm/pumba#43]
Problem 1: If the default user is set to something other than root, pumba fails. Example:

    docker create -u=node --name node_test node:8.2.1 sleep 10000
    docker create -u=root --name root_test node:8.2.1 sleep 10000
    docker start node_test root_test
    echo "run as node, this one fails"
    pumba --random netem --duration 5s delay -t 200 node_test
    echo "run as root, this one succeeds"
    pumba --random netem --duration 5s delay -t 200 root_test
    docker container rm --force node_test root_test

Problem 2: When it fails, it fails with the rather useless message `command 'tc' failed in /node_test (<image id>) container; run it in manually to debug`
It would be very useful to have the actual output of the failed command present, possibly hidden behind the --debug flag. In my case, I was (and still am) unable to successfully run the tc command outside of the context of pumba, so it was very difficult to debug it. In my case, the command output would have been mostly useless, but I wouldn't have spent a day getting it before finding that out.

**Comment by alexei-led** [comment]
@polson136, Did you try to run with `--tc-image` flag? It will launch a sidekick container with `tc` tool onboard, attaching to the same network as target container.
