### ISSUE TITLE
Building Error - "golang:1.8-alpine AS builder"

### ISSUE THREAD

**Issue by Spellchaser** [gaia-adm/pumba#45]
I tried building with Docker and getting this error. Pumba binary runs fine, but I wanted to try to build it. This is on a RHEL 7.3.

```
user@box pumba]$ docker build -t pumba -f Dockerfile .
Sending build context to Docker daemon 38.68 MB
Step 1 : FROM golang:1.8-alpine AS builder
Error parsing reference: "golang:1.8-alpine AS builder" is not a valid repository/tag
```

**Comment by Tyson1986** [comment]
I have just tried the same command for build and all works as exected (on macOs Sierra 10.12.6 Docker Version 17.06.2-ce-mac27), also i see 'golang:1.8-alpine' in dockerhub registry.

**Comment by Spellchaser** [comment]
Ahh it's a corp proxy issue.
