### ISSUE TITLE
Fix `netem` when destination IP filter is defined

### ISSUE THREAD

**Issue by alexei-led** [gaia-adm/pumba#52]
Thanks to Alexey Krutilko

This need to be implemented inside Pumba `netem` command

The right sequence of commands to implement should be:

1. `tc qdisc add dev eth0 root handle 1: prio` - start new queue disc but no classes yet
2.`tc qdisc add dev eth0 parent 1:2 handle 30: netem delay 150ms` - add 3 classes, `1:2` default class, all traffic goes through it with delay of 150ms
3. `tc qdisc add dev eth0 parent 1:3 handle 20: netem delay 500ms` - no new classes created, but delay is specified for `1:3`, traffic still goes through `1:2`
4. `tc filter add dev eth0 parent 1: protocol ip prio 1 u32 match ip dst 172.17.0.3 flowid 1:3` - add destination filter by IP and now all traffic to this IP will go through class `1:3`

**Comment by T-Eberle** [comment]
+1

**Comment by alexei-led** [comment]
Fixed in 0.4.7

**Comment by T-Eberle** [comment]
Works like a charm. Thx!
