### ISSUE TITLE
Are you planning to support Kubernetes or OpenSHift ?

### ISSUE THREAD

**Issue by roldancer** [gaia-adm/pumba#6]
Is there any plan to support Kubernetes/OpenShift?

Thanks.

**Comment by alexei-led** [comment]
You can always mannualy run Pumba in Docker container on each node you want to make chaos, like this:
```
docker run -d -v /var/run/docker.sock:/var/run/docker.sock gaiaadm/pumba --chaos "re2:^hp|10s|KILL:SIGTERM"
```

I will also add a Kubernetes deployment manifest, using DaemonSets. This will allow to automatically start Pumba on each managed host node.

I have no experience with OpenShift, and will gladly accept any contribution.

**Comment by alexei-led** [comment]
Now it is possible to deploy Pumba on CoreOS or Kubernetes cluster. Not properly testes, but should work.
