### ISSUE TITLE
custom built container kills itself

### ISSUE THREAD

**Issue by grosser** [gaia-adm/pumba#62]
we are only allowing images from our private registry, so I'm building my own with:
```
FROM gaiaadm/pumba@sha256:1558eef9460c1ed92cd83a8275edfa47c7ab85c5ffd9575facf3640e742c4321
CMD ["pumba", "--debug", "--random", "--interval", "3m", "--json", "kill"]
```

but it always kills itself:

```
[23:05:36]   {"level":"info","msg":"Killing /k8s_POD_kube-chaos-wg9bq_pod105_f1525f5b-e447-11e7-9882-02d46b998850_0 (515e04dab8481a3ed53a4a0642e72544327ef37bfceee9203794890b8472a03b) with signal SIGKILL","time":"2017-12-18T23:05:32Z"}
```

so need to hack around https://github.com/gaia-adm/pumba/blob/1e54a816a205fa5bae6bafcdf9b0e317206728bb/container/container.go#L76-L83

**Comment by alexei-led** [comment]
Running `pumba` *properly* on K8s requires more work on my side. Still had no time to complete it.

**Comment by grosser** [comment]
fixed by https://github.com/gaia-adm/pumba/pull/66
